version = 0.1
[default.deploy.parameters]
stack_name = "maily"
resolve_s3 = true
s3_prefix = "maily"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "HostedZoneId=\"Z01385783JRPHGDPC2JAH\""
