AWSTemplateFormatVersion: '2010-09-09'
Description: An SES email stack.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: ses-stack
    Description: SES stack setup with Easy DKIM.
    Author: Andy Caine
    SemanticVersion: 0.1.0
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['ses']
    HomePageUrl: https://github.com/andycaine/ses-stack#readme
    SourceCodeUrl: https://github.com/andycaine/ses-stack

Parameters:
  EmailDomain:
    Type: String
    Description: The domain you want to use for your email service.
  HostedZoneId:
    Type: String
    Description: The hosted zone ID for the domain.

Resources:

  EmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref EmailDomain
      DkimAttributes:
        SigningEnabled: true
      DkimSigningAttributes:
        NextSigningKeyLength: RSA_2048_BIT

  DkimRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !GetAtt EmailIdentity.DkimDNSTokenName1
          Type: CNAME
          TTL: '300'
          ResourceRecords:
            - !GetAtt EmailIdentity.DkimDNSTokenValue1
        - Name: !GetAtt EmailIdentity.DkimDNSTokenName2
          Type: CNAME
          TTL: '300'
          ResourceRecords:
            - !GetAtt EmailIdentity.DkimDNSTokenValue2
        - Name: !GetAtt EmailIdentity.DkimDNSTokenName3
          Type: CNAME
          TTL: '300'
          ResourceRecords:
            - !GetAtt EmailIdentity.DkimDNSTokenValue3
